-- LEGUAJE SQL (LENGUAJE DE COSULTA ESTRUCTURADA) 

-- CREAR UNA BASE DE DATOS

CREATE DATABASE PROBANDO1;

CREATE DATABASE PROBANDO2;

-- BORRAR UNA BASE DE DATOS
DROP DATABASE PROBANDO1;

DROP DATABASE PROBANDO2;